### PR TITLE
Add CFF export

### PR DESCRIPTION
**Pull request by adam3smith**
https://forums.zotero.org/discussion/101421/from-zotero-to-citation-cff#latest

### CODE REVIEW

**Comment by adam3smith** [comment]
A couple of open questions:
- Should we do something with other item types? CFF-type is explicitly only valid for software and dataset, so I'd be inclined to say no.
- Should we add some sort of message at the top? E.g. this is what cff files generated with cffinit display. I find the second line tacky, but clarifying origin might be worthwhile?:

> \# This CITATION.cff file was generated with cffinit.
> \# Visit https://bit.ly/cffinit to generate yours today!

- The are various places for the URL. It could be identifier: - URL or repository-code: I currently don't handle it at all, but it should probably be somewhere?

**Comment by dstillman** [comment]
> Should we do something with other item types? CFF-type is explicitly only valid for software and dataset, so I'd be inclined to say no.

Yeah, I think that's fine.

> Should we add some sort of message at the top?

Sure, `This CITATION.cff file was generated with Zotero.` seems appropriate.

> The are various places for the URL.

Just `url:` seems fine.

**Comment by adam3smith** [comment]
> Just url: seems fine.

oh, I had overlooked that, that makes sense.

I think this is read then. One last question: there is not a way I can set the filename of the exported file, is there? That should be `CITATION.cff`, not `Exported Items.cff`, ideally.

**Comment by dstillman** [comment]
> there is not a way I can set the filename of the exported file, is there?

Hmm, no, though we could just hard-code that for this translator in the app. We could add proper support for it, but I'm not sure we've ever had another need for it.

**Comment by adam3smith** [comment]
> We could add proper support for it, but I'm not sure we've ever had another need for it.

I agree -- I think it'd be nice to hard-code this for CFF, but otherwise it has never come up.

**Pull request merged**
