### PR TITLE
Create General Biographical Dictionary fromoldbooks.js

### PR DESCRIPTION
**Pull request by guitarzxt**
A scraper for the General Biographical Dictionary

### CODE REVIEW

**Comment by aurimasv** [comment]
See comments on https://github.com/zotero/translators/pull/1035. Also please add tests. I cannot find the page for Chalmers Biography, so I can't really comment on anything specific.

**Comment by guitarzxt** [comment]
http://words.fromoldbooks.org/Chalmers-Biography/

**Comment by AbeJellinek** [comment]
@guitarzxt, could you rewrite without FW? If you did that, I'd be happy to merge this in.

**Comment by AbeJellinek** [comment]
Closing this; no progress since 2016, uses FW.

**Pull request closed without merging**
