### PR TITLE
PICA: Adding links to the online document

### PR DESCRIPTION
**Pull request by eonm-abes**
This PR adds links to online document for PICA based catalogs. Links are stored in the url field of Zotero.

__About tests :__

* For links extraction : I added tests for all PICA catalogs already cited in the tests.
* When possible I updated the tests. I keep three of them untouched because of errors (these error are not related to link extraction but to UI changes) :
http://cbsopac.rz.uni-frankfurt.de/DB=2.1/PPNSET?PPN=318490412
http://gso.gbv.de/DB=2.1/PPNSET?PPN=768059798
* I deleted tests for catalogue.rug.nl which seems not  to be active anymore. It's looks like they're using a new catalog system (https://rug.on.worldcat.org/)

Best regards

### CODE REVIEW

**Comment by AbeJellinek** [comment]
This looks good to me. In the future, please prefix commits with the translator's name (like you did in the PR title)! Not a big issue, though.

**Comment by AbeJellinek** [comment]
Actually, on second thought - changes look technically good, but is there precedent for this? A glance through other library translators isn't turning up any that store online resource URLs in the Zotero item. Could you describe why it's important here?

**Comment by adam3smith** [comment]
Yes, we do this where we know a URL is an actual document/full text, see e.g.
https://github.com/zotero/translators/blob/master/Primo%20Normalized%20XML.js#L280

**Comment by AbeJellinek** [comment]
Ah, OK, great. Thanks for clarifying.

In that case, I'll merge this in and look into fixing the two now-incompatible catalogs in the tests.

@eonm-abes, thanks for your contribution!

**Comment by eonm-abes** [comment]
Hi @AbeJellinek,

Sorry for the late reply, I didn't see GitHub notifications.

> This looks good to me. In the future, please prefix commits with the translator's name (like you did in the PR title)! Not a big issue, though.

I will try to remember that!

Thank you

**Pull request merged**
