### PR TITLE
SIRS Knowledge Source [new translator]

### PR DESCRIPTION
**Pull request by sircmyst**
New translator for SIRS Knowledge Source, a ProQuest K-12 database
(Note: this only covers Knowledge Source, not SIRS Discoverer or SIRS Decades)

### CODE REVIEW

**Comment by sircmyst** [comment]
Hi there, figured I'd poke in and see how things were moving along? (just in case my last message got missed during the holidays)

**Comment by aurimasv** [comment]
Can you update tests using latest version of scaffold and then squash all commits? This looks ok to merge.

**Comment by sircmyst** [comment]
I've installed the latest version of Scaffold, and the tests are updated and running successfully. The branch has been force pushed with squashed commits.

**Comment by aurimasv** [comment]
Thank you!

**Pull request merged**
