### PR TITLE
new translator for Peeters from @zuphilip 's workshop #1582

### PR DESCRIPTION
**Pull request by socheres**

### CODE REVIEW

**Comment by socheres** [comment]
thanks @zuphilip The translators for Peeters doesn't work with [Byzantion ](http://poj.peeters-leuven.be/content.php?url=issue&journal_code=BYZ&issue=0&vol=87). I tried to fix the title/subtitle with several xpath option, but there aren't global pattern. 

`	item.title = ZU.xpathText(doc, '//b[contains(text(), "Title:")]/following-sibling::text()[1]|//b[contains(text(), "Title:")]/following::i[1]|//b[contains(text(), "Title:")]/following-sibling::text()[2]', '', '');
	var subtitle = ZU.xpathText(doc, '//b[contains(text(), "Subtitle:")]/following-sibling::text()[1]|//b[contains(text(), "Subtitle:")]/following::i[1]', '', ''); 
	if (subtitle) {
		item.title = ZU.trimInternal(item.title += ': ' + subtitle);
	}` 

It is better to load first a import translator e.g. from mEDRA? and then to scrape missing items like subtitle, volume, issue, abstracts. It was my mistake to send pull request of all my commits to zotero/master.

**Comment by zuphilip** [comment]
Okay, I created now a new PR with Peeters translator only see #1606. Moreover, I adapted the extracting methods such that it works with the example above and also with another example where the author is only given in initials (and therefore the allcaps test is failing).

**Comment by socheres** [comment]
thanks @zuphilip here in my latest [commit](https://github.com/zotero/translators/pull/1597/commits/cd481b9b01431668ec63273177345db805d5dda6)  some more fixes that i found.

**Comment by zuphilip** [comment]
(The changes for Dialnet with some update I put it here #1613, but please don't add it to this branch again.)

**Comment by socheres** [comment]
thank you @zuphilip for your changes and PR.

**Comment by adam3smith** [comment]
superseded by https://github.com/zotero/translators/pull/1606

**Pull request closed without merging**
