### PR TITLE
save full-res versions of any images in tweet

### PR DESCRIPTION
**Pull request by wildthyme**
a snapshot of the page only saves the low-res version of tweet images. this downloads and adds them as additional attachments

### CODE REVIEW

**Comment by wildthyme** [comment]
RIP i messed up the style ig

**Comment by zuphilip** [comment]
I am hesitant that saving the images in high resolution from Twitter is that common for the users of reference management software. @adam3smith Was anything like this asked before in the forum?

**Comment by zuphilip** [comment]
Maybe https://www.zotero.org/support/preferences/hidden_preferences#zotero_connector

**Comment by adam3smith** [comment]
@wildthyme Do you have an example where this matters? As far as I can tell, the Snapshot does save the full size pic, though there's not easy way to get it to show.

**Comment by zuphilip** [comment]
Closing this pull request because of inactivity. @wildthyme, if you want to continue here, then feel free to reopen it.

**Pull request closed without merging**
