### PR TITLE
sudoc new URL (cbs/ path) is captured again

### LINKED ISSUE #2202: [PICA] sudoc broken
Two years ago there had been an issue with http://www.sudoc.abes.fr/ that was not working properly ( #1529 ). @zuphilip had provided a quick fix by rewriting the base url.

The issue is with multiple results page. It works fine on a single record page, but for multiple, the list of available records is displayed, but trying to get one crashes.

But it appears that, following an update on their website, it is broken again. There is an extra cbs/ path in the url. I have tried to fix it by replacing the previous fix : 

```
newUrl = newUrl.replace(/sudoc\.abes\.fr\/cbs\/\/?DB=/, 'sudoc.abes.fr/cbs/xslt/DB=');
```

But it does not appear to work, if anybody has an idea on how to fix it.

### PR DESCRIPTION
**Pull request by kerphi**
fixes #2202 issue

cc @symac

### CODE REVIEW

**Comment by adam3smith** [comment]
We'll take this as is, but if someone would be willing to lint it (which is a bunch of manual work) that'd be great.

**Comment by adam3smith** [comment]
@symac Thanks! Could you rebase this into **two** commits: One for the first two issues that fix the problem, one for the second two that fix linting?

**Comment by kerphi** [comment]
@adam3smith I think it's ok, I just rebased the lint stuff into one commit and and rebased the bug fix commits into one commit.
Tell me if it's ok?

cc @symac

**Comment by adam3smith** [comment]
Perfect, thank you!

**Pull request merged**
