### PR TITLE
Update TEI translator for changes in 2.8.

### PR DESCRIPTION
**Pull request by adunning**
See <http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.citing.html> for the documentation (and <https://listserv.brown.edu/archives/cgi-bin/wa?A2=TEI-L;e784a172.1412> for further explanation).

### CODE REVIEW

**Comment by adam3smith** [comment]
Note open TEI PR here: https://github.com/zotero/translators/pull/934

**Comment by adunning** [comment]
I hadn't noticed that; thanks! This deals with a separate (and fortunately simpler) issue that is blocking Zotero-generated files from validating.

**Comment by aurimasv** [comment]
Yeah, that's ok. I don't have any perspective on this, so unless @adam3smith objects, we can merge and deal with the other PR later.

**Comment by adam3smith** [comment]
no, no objections, just wanted the two PRs linked.

**Comment by adunning** [comment]
Thanks!

**Pull request merged**
