### PR TITLE
Update wikipedia citation templates format

### PR DESCRIPTION
**Pull request by bunyk**
And fix pipe errors in titles

### CODE REVIEW

**Comment by adam3smith** [comment]
@owcz could I ask you to check if this makes sense? No need to check syntax, but I'd like someone with WP knowledge to take a look at the changed output.

**Comment by owcz** [comment]
Yep, the line breaks are non-standard (sometimes written like that to make the citations easier for humans to read, but not efficient within articles). For standard web citation formats, see [this section](https://en.wikipedia.org/wiki/Template:Cite_web#Examples). As for the `<ref>` tags, that's also a non-standard user preference. The citations don't necessarily need them, depending on how the bibliography is built.

I had actually rewritten this script several years ago but I just never cleaned it up for production and edge cases... Part of the problem here is that there will be a high variance in what different users will want off of the base citation (changing the date format, whether to put an asterisk or `<ref>` in front of the built citation, etc.) I remember there not being good options for dealing with that within Zotero, so I had worked on my own tools outside of it.

**Comment by adam3smith** [comment]
Thanks! So @bunyk -- I'm not convinced we want the other changes, then (I'm open to be convinced, though; I have no stake in this except to get it right). 
Just so I understand the actual fix you're proposing here -- pipes are escaped as {{!}} in the template? That seems odd -- but if that's the case, the solution is fine and we'll take it.

**Comment by owcz** [comment]
The pipe escaping is good, as pipes are used to delineate between params in the Wikipedia citation style. If not escaped, the pipes cause havoc.

**Comment by bunyk** [comment]
@adam3smith Yes, all this actually is copied from my own setup. I made this pull request minimal.

**Comment by adam3smith** [comment]
thanks & sorry for the delay in merging this

**Pull request merged**
