### PR TITLE
[RIS] Store research notes (RN) as note attachments

### PR DESCRIPTION
**Pull request by aurimasv**
Re https://forums.zotero.org/discussion/46548/importing-research-notes-from-endnote-to-zotero/

Don't see any downside and this makes sense, IMO, but would like someone to second this.

### CODE REVIEW

**Comment by zuphilip** [comment]
Are the examples realistic? I don't see any downsides but I am thinking if a note or a tag is better... BTW you will review #845 further?

**Comment by aurimasv** [comment]
If you're referring to the test case, then that's just a collection of all field labels (as displayed in EndNote). It's only meant to help us figure out if we're mapping things correctly.

**Comment by zuphilip** [comment]
Yes, I was refering to the test cases.

**Comment by aurimasv** [comment]
>BTW you will review #845 further?

Yes, I'm working my way up from some older pull requests.

**Pull request merged**
