### PR TITLE
Create Vox.js

### PR DESCRIPTION
**Pull request by owcz**
translator for vox.com

### CODE REVIEW

**Comment by owcz** [comment]
I was able to pull lots of simple metadata for this one. Would it be be better to merge date and author detection into the standard metadata scraper instead? That would be:
```
creators         : FW.Xpath('//meta[@name="author"]/@content').text().cleanAuthor("author"),
date             : FW.Xpath('//meta[@property="article:published_time"]/@content').text().split("T"),
```
(The metadata scraper only pulled the title and description without this translator.)

Also the multiple looks like it's handled by Google CSE—is there a translator that does that already? I would think that it's a common multiple to detect.

**Comment by adam3smith** [comment]
Yes, I'd like these added to EM. There is an open ticket for article:property type metatags:
https://github.com/zotero/translators/issues/932

The meta[@name="author"] is a basic HTML metatag. I guess concern here might be that data quality is too low, but I think it should be fine. http://www.w3schools.com/tags/att_meta_name.asp.

I don't think we have a recyleable implementation of a google CSE, so we'd need that for sure. 

So let's wait on this translator & I'll see what I can do with EM (or you can, if you're feeling adventurous).

**Comment by adam3smith** [comment]
@owcz -- OK, the EM/RDF changes are now live and the Vox.com data all imports. If you still want to do this, you can simply call the EM translator for pages and would just have to call multiples.

**Comment by owcz** [comment]
@adam3smith – nice! Looks good. Only thing I'd add is that it might be good to support the "language" parameter, and that it might be worth splitting the date (`2016-01-16T16:00:03Z` → `2016-01-16`), though I know Zotero usually does that on export anyway.

**Comment by adam3smith** [comment]
for language you mean the lang attribute of html? Looks like that might be worth it, yes. Not sure how often that turns out to be wrong, though. We'd be particularly concerned about false positive "en" declarations, since those will mess with citation styles. I looked at a couple of larger newspapers and they're all correct (Spiegel, Le Monde, El Pais), but less certain about smaller sites. 

If you look at how the data actually imports, Zotero understands the date including the time internally, so I don't see any reason to chop off the time. Some people may enjoy having it included (e.g. if you study something like online journalism) and as you say, it's getting ignored on export, both to citations and to export formats.

**Comment by owcz** [comment]
The original pull request had `language         : "en-US",`, which doesn't appear to trigger in EM—just wanted to make sure it was accounted if necessary. Re: the latter, sounds good

**Comment by adam3smith** [comment]
oh right. If you were to write a translator, you'd have to explicitly set that in the item handler. The EM translator can't get that at the moment and as per above I'm not sure if we should get it from the only place I currently see it on vox.

**Pull request closed without merging**
