### PR TITLE
EBSCO Hotfix for discovery layer

### PR DESCRIPTION
**Pull request by adam3smith**
https://forums.zotero.org/discussion/88250/zotero-connector-does-not-offer-all-sources-in-database-results#latest

### CODE REVIEW

**Comment by adam3smith** [comment]
Question @adomasven @dstillman  -- is it possible to disable the push test, since that will always fail?

**Comment by dstillman** [comment]
For specific translators, you mean?

**Comment by dstillman** [comment]
We could add something to the translator metadata and have CI look for it.

**Comment by adam3smith** [comment]
No, I'm always seeing two tests:
image

The (pull_request) one is the real test and that should always run. The (push) one always fails with a version of

```
fatal: ambiguous argument '0a03ebbf4cbf1a1b8140f11f65b2337fc5632eca^^!': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Error: Process completed with exit code 128.
```

(and, emails that to me). I don't see any reason for that to ever run unless I'm missing something

**Comment by adam3smith** [comment]
See also the above -- the relevant test now passes, but PR is still marked as failing in the overview

**Pull request merged**
