### PR TITLE
Re-introduce changes from #1814

### PR DESCRIPTION
**Pull request by adam3smith**
But this time without breaking stuff...

### CODE REVIEW

**Comment by retorquere** [comment]
(not that it's any kind of excuse for my error, but why didn't the test suite pick this up?)

**Comment by retorquere** [comment]
I see now, travis only does a lint check. This looks good to me.

**Comment by adam3smith** [comment]
Yeah, more advanced CI for translators would be nice, especially since most translators already have built in unit tests (wouldn't have helped here because export translators don't). @zuphilip and @dstillman talked about this briefly when they implemented the current CI but I forgot where that was left. Obviously the overhead to run the tests is pretty significant, so this isn't a trivial problem.

**Comment by retorquere** [comment]
Already working on both. Current tests run in a second or two.

**Comment by retorquere** [comment]
(and I've already found a few errors in existing translators)

**Comment by zuphilip** [comment]
There is a ticket for supporting export translators in Scaffold https://github.com/zotero/scaffold/issues/103 and I would appreciate also automatic tests for export translators.

I guess that now with the new [translation-server](https://github.com/zotero/translation-server) it is more easily possible to include to run also automatically the test cases for each pull request or commit. As most PR are changing only a single translator, it is enough to test these test cases and that shouldn't take that long.

**Comment by dstillman** [comment]
> Already working on both. Current tests run in a second or two.

Not sure what you're referring to here, but we have a [ticket](https://github.com/zotero/translators/issues/1310) for CI-based testing of translator commits. This would be separate from the [existing daily translator tests](https://translator-tests.zotero.org/), though it would use the [same Node-based testing functionality](https://github.com/zotero/provo/blob/94c6fa691005e5935f58209aaf557723bbd2a6b9/test_v2.sh#L30). (Web translators can easily fail when run that way because JS isn't run, but import/export tests should never fail.)

If you're working on this, it might be worth posting to that ticket to make sure you're not doing unnecessary work.

**Pull request merged**
