### PR TITLE
Update MODS.js

### PR DESCRIPTION
**Pull request by bwbohl**
add Marc relators cmd (Composer) to roleTerms

### CODE REVIEW

**Comment by dstillman** [comment]
Thanks. For this to be pushed to users, the lastUpdated timestamp needs to be updated as well.

**Comment by bwbohl** [comment]
> Thanks. For this to be pushed to users, the lastUpdated timestamp needs to be updated as well.

yeah just realised, from the travis log thanks!
Apparently indentation needs to be fixed, too…
I'm just wondering how I can test the export locally before committing or merging. Any help appreciated ;-)

**Comment by dstillman** [comment]
Don't worry about the linting (unless it's in lines you changed) other than the timestamp — we can clean it up separately. (You're welcome to, in a separate commit, but it's not necessary.)

Testing locally is a little tricky because export translators aren't currently supported in Scaffold (Tools → Developer → Translator Editor), but you'd want to make this change to MODS.js in the 'translators' directory of your <a href="https://www.zotero.org/support/zotero_data">Zotero data directory</a> and then restart Zotero to test it.

**Comment by dstillman** [comment]
You should actually drop that indentation commit — that changes lots of lines unnecessarily and isn't what the linter is complaining about. (We happily use indents to match surrounding indentation on blank lines.)

**Comment by bwbohl** [comment]
ok I'll fix lines 947–955 indentation, but what about the travis log: "17:20 browserSupport set, but translatorType (3) does not include web (4)"

**Comment by bwbohl** [comment]
just converted this to a draft as I still have to test locally

**Comment by dstillman** [comment]
Yeah, you can remove the browserSupport line in the linter commit. This is an import translator, so that line isn't relevant.

Once you've tested this, can you rebase and squash (or reset and add -p) into two separate commits, one for the change and one for the linter?

**Pull request closed without merging**
