### PR TITLE
Education Week: Complete re-write

### PR DESCRIPTION
**Pull request by adam3smith**

### CODE REVIEW

**Comment by adam3smith** [comment]
Another ping here @dstillman : any idea what's going on with CI? Should I just proceed without it (checked against teslint locally)

**Comment by dstillman** [comment]
Sorry, we're out of Travis credits after they stopped giving those to open-source projects. We need to port this repo to GitHub Actions — already moved zotero/zotero over but haven't yet done it for this one. Will try to do it soon.

Fine to go ahead without it in the meantime

**Comment by dstillman** [comment]
OK, probably will need to do more tweaking after seeing it with actual PRs and commits, but in theory we're up and running on GitHub Actions. You can try to rebase on master and see how it goes.

**Comment by adam3smith** [comment]
Hmm -- the check looks good, so that's great, but I don't understand what I did wrong with the rebase, any ideas? I rebased against local master after `pull upstream master`, but that shouldn't matter, right?

**Comment by dstillman** [comment]
Did you do `pull upstream master` while on this branch, or on `master`? If the former, you would've merged into this branch. I'd strongly recommend either `git config --global pull.ff only` or `git config --global pull.rebase true` to prevent automatic merge commits. The former gives you more control. I use the latter.

In any case, while on this branch, the easiest thing is to just do `fetch upstream master` and then `rebase -i upstream/master`. You can later switch to `master` and do `pull` (which at that point would just be a `merge`, because you had already fetched, if there hadn't been any other remote commits).

**Comment by dstillman** [comment]
The PR check here didn't actually work, but let's see what happens after a proper rebase.

**Comment by dstillman** [comment]
I've updated master with some additional fixes for the checks.

**Comment by adam3smith** [comment]
Thanks -- the rebase worked (thanks for the tip about the global config, too), but it looks like the CI workflow didn't run correctly.

**Comment by dstillman** [comment]
That's not rebased on the latest master commit.

**Comment by adam3smith** [comment]
hmmm. I followed instructions above and looked good.

```
$ git log

commit 71a3ffa2275a4736fe945166d093ff832559d49b (HEAD -> edweek, origin/edweek)
Author: Sebastian Karcher <karcher@u.northwestern.edu>
Date:   Fri Jan 29 23:40:16 2021 -0500

    Education Week: Complete re-write

commit d50a2dadd4e6b69326a0f3fb61f3c1a48e9724d7 (upstream/master)
Author: Dan Stillman <dstillman@zotero.org>
Date:   Sat Jan 30 18:03:48 2021 -0500

    CI: Fetch additional history twice

    For some reason the first `git fetch --depth=25` sometimes isn't
    working to fetch additional history on the shallow clone. No idea why
    not.

commit e7432cf1ead874ecc453abca2aa6971c6989e913
Author: Dan Stillman <dstillman@zotero.org>
Date:   Sat Jan 30 18:03:35 2021 -0500

    CI: Bail on failure to get translators to check

    Wrap grep so that we can use -e for check-pull-request.sh and lint.sh

**Comment by dstillman** [comment]
Yeah, sorry, that's correct — I must've been looking at something else.

Can you try rebasing again off the latest master?

**Comment by adam3smith** [comment]
No luck

```
$ git log
commit 14772adc58c220d40d2a2be66ec2ebff6579ad12 (HEAD -> edweek, origin/edweek)
Author: Sebastian Karcher <karcher@u.northwestern.edu>
Date:   Fri Jan 29 23:40:16 2021 -0500

    Education Week: Complete re-write

commit d968b5cdf28cc4eba205c9937f21c5eeabf84a16 (upstream/master)
Author: Dan Stillman <dstillman@zotero.org>
Date:   Sun Jan 31 23:42:35 2021 -0500

    CI: Fix error on master, hopefully

commit cfe7c510cd62a0dff53ccbe4a9216422b9fbeb6d
Author: Dan Stillman <dstillman@zotero.org>
Date:   Sun Jan 31 23:27:44 2021 -0500

    CI: Try a different approach to fetching additional history
```

**Comment by adam3smith** [comment]
It's referencing https://github.com/zotero/translators/commit/85b2fc0eecbae74e15784b171451ffebfad2b010 which is a merge commit that doesn't show up anywhere else ???
Possible this is just an issue related to rebase+force push and will work on regular PRs?

**Comment by dstillman** [comment]
It won't fix the error but can you rebase again just to confirm that we're failing properly on error now?

**Comment by adam3smith** [comment]
I take it that's the desired result?

**Comment by dstillman** [comment]
OK, you can ignore the errors and merge this if you want. I was able to reproduce this by opening a test PR, which handles merging differently from a regular branch, which I was using to test this.

**Comment by dstillman** [comment]
OK, I think we're good. Try rebasing again.

**Comment by adam3smith** [comment]
Yay! Both lint and tests running, thanks!

**Pull request merged**
