### PR TITLE
Add UNZ Print Archive.js

### PR DESCRIPTION
**Pull request by owcz**
Translator for UNZ.org periodical archive. Really powerful—works on every page (save for individual books without reviews, which don't have useful metadata and for which users are better off clicking through to their Internet Archive source).

### CODE REVIEW

**Comment by owcz** [comment]
## ready for review
* removed [Framework](https://www.zotero.org/support/dev/translators/framework) per #1277
* multi support for issue pages, search
* only covers the print archive (unz.com/print, formerly unz.org) and not the new conservative blog unz.com

**Comment by owcz** [comment]
@adam3smith i have a bunch of translators ready for review but buried in the queue—wanted to make sure you saw

**Comment by zuphilip** [comment]
Busy times for me as well...

**Comment by AbeJellinek** [comment]
I'm sorry this sat in the backlog for so long! Great translator and a really cool site that I'm glad I know about now.

**Pull request merged**
