### PR TITLE
Add alternate mappings for 'a' with ring diacritic

### PR DESCRIPTION
**Pull request by GuyAglionby**

### CODE REVIEW

**Comment by GuyAglionby** [comment]
There are a lot of linting fixes here -- happy to deal with them, but didn't want to jump the gun in case there were other plans for this file as it'll be quite time-consuming.

**Comment by retorquere** [comment]
A lot of the lint complaints can be fixed automatically by running `npm run lint -- -- fix BibTeX.js` I can do it for you if you want.

**Comment by retorquere** [comment]
I don't know how to do PRs on PRs, but I've applied lint-fixing to your PR [here](https://gist.github.com/66c60170af0824ece5448b2149a2922d). There's one remaining:

```
1013:5   error    Function 'beginRecord' expected no return value                      consistent-return
```

but I really don't understand this function so I'm hesitant to touch it.

**Comment by AbeJellinek** [comment]
Linting doesn't seem appropriate for this PR, but this looks like a good change to me. Merging.

**Pull request merged**
