### PR TITLE
Create State Records Office of Western Australia.js

### PR DESCRIPTION
**Pull request by ontomoc**
This is a Zotero translator for State Records Office of Western Australia's archive catalogue at https://archive.sro.wa.gov.au/index.php/.  The catalogue is an AtoM-based system (http://accesstomemory.org).

The translator harvests metadata for (a) Series, (b) Items, (c) Pieces.  It also will harvest metadata for multiple items returned from a catalogue search.

### CODE REVIEW

**Comment by adam3smith** [comment]
Thanks -- so before we get to the details: we're actually trying to phase out use of Framework translators: they use a very large chunk of duplicate code, are limited in what they actually let you do, and given the availability of good helper function and template code, provide very little benefit. Your regular javascript seems quite solid, so it wouldn't seem so hard to just change this to a regular translator, if you'd be up for that?
https://www.mediawiki.org/wiki/Citoid/Creating_Zotero_translators

**Comment by zuphilip** [comment]
Ping @ontomoc

**Comment by zuphilip** [comment]
@ontomoc @adam3smith What is the status of this PR? Is this ready for review?

**Comment by ontomoc** [comment]
Ready for review.  The final code is at https://github.com/zotero/translators/pull/1701.  Somehow https://github.com/zotero/translators/pull/1422 got behind (my github error I think).

**Comment by zuphilip** [comment]
Superseeded by #1701 therefore let us concentrate there.

**Pull request closed without merging**
