### PR TITLE
Zenodo2023

### PR DESCRIPTION
**Pull request by aborel**
This pull requests updates the Zenodo web translator to work with the new InvenioRDM platform https://blog.zenodo.org/2023/10/13/2023-10-13-zenodo-rdm/

DOM selectors have been modified to match the new structure, and the tests have been updated due to minor JSON changes in Zenodo.

### CODE REVIEW

**Comment by dstillman** [comment]
This looks great, but could you rebase this on current `master` and force-push for a commit log in this PR?

**Comment by aborel** [comment]
Certainly better now, I hope it's enough.

**Comment by dstillman** [comment]
No, you can see it still says above that there are 94 commits in this PR, by you and others. You'll want to fetch the upstream `master` (i.e., this repo) and then rebase your `zenodo2023` feature branch on that.

**Comment by aborel** [comment]
Sorry if it's a naive question, but I think I am quite confused about this step. I understand that the PR needs to contain only the relevant commits for the one modified file, but currently I am stuck trying to get rid of the unnecessary details of a previous PR. I have been following the procedure described by https://medium.com/@topspinj/how-to-git-rebase-into-a-forked-repo-c9f05e821c8a but is complaining about conflicts regarding the old project that was closed weeks ago, but I don't understand how to just move on and ignore these. This is my second PR ever, so I am still learning the good practices... can you enlighten me?

**Comment by dstillman** [comment]
Hard to help without knowing the exact history of your feature branch, but in this case you can just make a copy of this file outside the folder, do `git fetch upstream master` followed by `git reset --hard upstream/master` (which will delete all changes), copy the file back, make a new commit with just that file, and force-push. (This is assuming `upstream` is this repo, which you can see with `git remote -v`. If `origin` is this repo, use that instead for both commands.)

**Comment by dstillman** [comment]
In general, for a PR, you would make sure you were always starting a feature branch from a freshly fetched copy of `upstream/master` (either literally `upstream/master` or just `master` if you're pulling it to a local branch). Then if you ever had to rebase, you would fetch `upstream/master` or pull it into your local `master` and `rebase -i` the feature branch on that. You would never want to start a feature branch from a branch that wasn't the latest commit in this repo.

**Comment by aborel** [comment]
I guess my original mistake was to work on the old project in my master branch. I tried to be smarter this time, but apparently I'm still carrying the burden of that unfortunate decision.
Let's see if I understand how to fix this: is there a clean way to rebase my master branch and merge it into the new zenodo2023 feature branch?

**Comment by dstillman** [comment]
You should just do what I said above. It's just a single file.

**Comment by dstillman** [comment]
This?

[Zenodo.js.zip](https://github.com/zotero/translators/files/13611770/Zenodo.js.zip)

**Pull request merged**
