### PR TITLE
Update Baidu Scholar

### PR DESCRIPTION
**Pull request by boan-anbo**
fixed RIS export url.

Things changed on Baidu's end:
1. First names abbreviated, e.g. `Pablo` to `P.`.
2. Non-lain characters latinized.

### CODE REVIEW

**Comment by boan-anbo** [comment]
#2432

**Comment by AbeJellinek** [comment]
Looks great, thanks! Could you run it through `npm run lint -- "Baidu Scholar.js" --fix` (or fix the lint issues manually)?

**Comment by boan-anbo** [comment]
Done!

**Comment by AbeJellinek** [comment]
OK, great. Thanks!

**Pull request merged**
