### PR TITLE
PQ-71894: fix results list error in zotero ProQuest translator

### PR DESCRIPTION
**Pull request by pmusson**

### CODE REVIEW

**Comment by pmusson** [comment]
Should fix the title undefined error we are seeing. Probably caused by a change in the proquest webapp markup

Also added to this fix the change to the new proquest url www.proquest.com  (search.proquest.com also still required)

**Comment by adam3smith** [comment]
Cool thanks -- you'd need to bump the timestamp, please, otherwise this doesn't actually update for users.

**Comment by pmusson** [comment]
Thanks, I've updated the timestamp

**Comment by adam3smith** [comment]
Thanks!

**Pull request merged**
