### PR TITLE
 Oxford English Dictionary: remove translator framework

### PR DESCRIPTION
**Pull request by retorquere**
How do I test translators that require authentication in scaffold? I have access through an institutional proxy.

### CODE REVIEW

**Comment by dstillman** [comment]
If you have direct, real proxy, or VPN access, it'll just work. If you only have a web-based proxy, you'd need to save the translator, reset translators in the connector preferences, and test pages manually in the browser.

**Comment by retorquere** [comment]
I have only web-based. I'll give that procedure a go.

**Comment by retorquere** [comment]
Well that's not great. The web-based proxy changes the url from http://www.oed.com/ into https://www-oed-com.vu-nl.idm.oclc.org/, so the url-based regex would fail. Suggestions? How have other translators dealt with this?

**Comment by dstillman** [comment]
That’s handled by the connector’s proxy support — the translator doesn’t have to deal with it. EZProxy proxies should be detected automatically. If yours is something different you may need to configure it manually in the connector prefs.

**Comment by retorquere** [comment]
I'm using EZproxy, but the Zotero icon doesn't change and OED is not one of the options under the Zotero browser button after updating the translators.

**Comment by retorquere** [comment]
I've submitted the connector log with debug Report ID: 5040489

**Comment by dstillman** [comment]
You should just configure your proxy in the Proxies pane of the connector preferences.

**Comment by retorquere** [comment]
I have this in my proxies: `%h.vu-nl.idm.oclc.org/%p`

**Comment by dstillman** [comment]
Are "Automatically associate new hosts" and "Automatically convert between dots and hyphens in proxied hostnames" checked?

If so, we'd want to see a <a href="https://www.zotero.org/support/debug_output#debug_output_logging">Debug ID</a> for loading the page when it's not detected. Make sure you've saved the translator in Scaffold and run Reset Translators first.

**Comment by retorquere** [comment]
Yes to both -- but I also see the yellow top-bar saying "Zotero redirected" etc while I'm not being redirected.

The "Entry" test now passes, but the multi-test does not. Still looking into that.

**Comment by retorquere** [comment]
I've logged the url from `detectWeb`, and I'm being handed https://www-oed-com.vu-nl.idm.oclc.org/search?searchType=dictionary&q=labor&_searchBtn=Search, so the regex fails.

**Comment by retorquere** [comment]
Changing the check to `/\/search\?/` seems to fix it, but previously the translator did check for the full URL.

**Comment by dstillman** [comment]
No, the target needs to match on the domain.

Can you provide a <a href="https://www.zotero.org/support/debug_output#debug_output_logging">Debug ID</a> from the connector for loading the page?

**Comment by retorquere** [comment]
D982078648

**Comment by dstillman** [comment]
Oh, you're talking about the `url` in `detectWeb`. That does give you the unproxied URL, but note that the previous version of the translator did, in fact, match only on the path, not the full URL. It's the job of the `target` to match the domain, and that comparison is to the proxied URL, which is working properly (or you wouldn't be getting to `detectWeb` at all). I'm not sure why the `url` in `detectWeb` isn't the proxied URL, but it doesn't really matter — there shouldn't really be a need to check the domain there.

In this case, we do need to make the `www.` in the target optional, however, since OED doesn't redirect.

**Comment by dstillman** [comment]
Oh, sorry, you're right — the MultiScraper did check the full URL. Yeah, don't worry about that — that was wrong. Checking just the path is fine, since the domain was already checked by the target.

**Comment by retorquere** [comment]
In that case it should be done as it is now.

**Comment by dstillman** [comment]
> In this case, we do need to make the `www.` in the target optional, however, since OED doesn't redirect.

**Comment by dstillman** [comment]
In other words: `"^https?://(www\\.)?oed\\.com"`

**Comment by dstillman** [comment]
Oh, while we're here, the target should end with `/`.

**Comment by zuphilip** [comment]
Is this ready for a review?

**Comment by retorquere** [comment]
It is for my part.

**Comment by AbeJellinek** [comment]
This looks great, thanks. Updated for a slight search page layout change and rebased.

**Pull request merged**
