### PR TITLE
Add Marc relators for soundRecording roles

### PR DESCRIPTION
**Pull request by bwbohl**
* new Relator Codes
  * Composer --> cmp: composer
  * Words By --> lyr: lyricist
  * Performer --> prf: performer
* remove some listing errors
* closes #2253

### CODE REVIEW

**Comment by dstillman** [comment]
Not sure why you opened this as a second PR? It's never necessary to open another PR when you already have one open against the same upstream branch — you can (and should) always rebase, squash, and force-push. It also doesn't make sense to have one PR closing another that you also control — you would have one closing an open issue with no code attached, or superseding another open PR that you can't close yourself.

In any case, if you only want one of these merged, you should close the other one.

Note that you're mixing tabs and spaces in this PR, so that will need to be corrected. There should only be tabs.

**Comment by dstillman** [comment]
Thanks, but you'll need to squash these into just two commits — the fix and the linting changes. If you need help doing that, I can point you in the right direction.

(We can squash into a single commit when merging via GitHub, but these should remain separate, and the alternative is our checking things out and squashing manually. This is why I said the linting changes weren't necessary.)

**Comment by bwbohl** [comment]
ok, sorry, was failing on squashing the commits and thought this'd be the easier way. (Also with closing the other PR from this one). Now again I seem to have failed on squashing commits after correcting the whitespaces to tabs (must have been some editor defaults going against me).
Help appreciated in getting it the way you want

**Comment by dstillman** [comment]
Two ways to do it:

1) `git rebase -i upstream master`, which should show just these four commits, and do an interactive rebase. You can read up on how to do that — it's incredibly useful — but here, basically, you'd want to move the last two commits after the commits they should be squashed with and change `pick` to `s` (for squash) on those lines. (You could use `f` for `fixup`, which squashes and throws away the commit messages, but in this case you'll want to reword the original commits so that they both begin with "MARC: ". When you're done, you'll end up with just two nicely descriptive commits.

2) Look at `git log`, make a note of the last commit on the branch before your changes, `git reset <that hash>` to unstage all your changes, and then use `git add -p` to pick the specific parts for each commit, committing them separately with appropriate descriptions. In a small commit like this where it's trivial to separate the changes and rewrite the commit messages, this way is a bit simpler.

**Comment by bwbohl** [comment]
thanks, for the tutorial!
hope we're there now
closed #2253 manually
wondering what travis-ci is stumbling over

**Comment by dstillman** [comment]
Yeah, Travis doesn't particularly like force-pushes.

Looks good. Can you just reword the second commit to begin with "MARC: ", so it's clear what translator it applies to? (Easy to do with an interactive rebase and `r`.)

**Comment by bwbohl** [comment]
done

**Comment by dstillman** [comment]
Er, right. Merged — thanks!

**Pull request merged**
