### PR TITLE
Add Open Review.js

### PR DESCRIPTION
**Pull request by hatimtachi**
Translator for https://openreview.net, an art news website

### CODE REVIEW

**Comment by adam3smith** [comment]
I have started a full review of the code, but before we spent too much time on this -- it strikes me as a much more promising approach to use the already embedded metadata for the translator and write something much simpler. See e.g. https://github.com/zotero/translators/blob/master/medes.js for a template. Any reason you're not doing that?

**Comment by adam3smith** [comment]
@hatimtachi let me know if you need any assistance here.

**Comment by AbeJellinek** [comment]
@hatimtachi, any progress with this?

**Comment by AbeJellinek** [comment]
Closing for lack of activity. EM works well for this site.

**Pull request closed without merging**
