### PR TITLE
Remove old extraToCSL format from translators

### LINKED ISSUE #1143: Deprecated prefix for fields in item.extra
I just search for code using `{:___: ___}` to save additional data in `item.extra`:

``` js
$ grep {: *.js
beck-online.js:         item.extra += "{:jurisdiction: europa.eu}";
beck-online.js:         item.extra += "{:jurisdiction: de}";
beck-online.js:                 item.extra += "\n{:genre: Beschl.}";
beck-online.js:                 item.extra += "\n{:genre: Urt.}";
beck-online.js:                         "extra": "{:jurisdiction: de}\n{:genre: Urt.}",
beck-online.js:                         "extra": "{:jurisdiction: de}\n{:genre: Urt.}",
beck-online.js:                         "extra": "{:jurisdiction: europa.eu}\n{:genre: Urt.}",
beck-online.js:                         "extra": "{:jurisdiction: de}",
BibTeX.js:              "input": "@article{Adams2001,\nauthor = {Adams, Nancy K and DeSilva, Shanaka L and Self, Steven and Salas, Guido and Schubring, Steven and Permenter, Jason L and Arbesman, Kendra},\nfile = {:Users/heatherwright/Documents/Scientific Papers/Adams\\_Huaynaputina.pdf:pdf;::},\njournal = {Bulletin of Volcanology},\nkeywords = {Vulcanian eruptions,breadcrust,plinian},\npages = {493--518},\ntitle = {{The physical volcanology of the 1600 eruption of Huaynaputina, southern Peru}},\nvolume = {62},\nyear = {2001}\n}",
BibTeX.js:              "input": "@article{zoteroFilePath1,\n    title = {Zotero: single attachment},\n    file = {Test:files/47/test2.pdf:application/pdf}\n}\n\n@article{zoteroFilePaths2,\n    title = {Zotero: multiple attachments},\n    file = {Test1:files/47/test2.pdf:application/pdf;Test2:files/46/test2-min.pdf:application/pdf}\n}\n\n@article{zoteroFilePaths3,\n    title = {Zotero: linked attachments (old)},\n    file = {Test:E:\\some\\random\\folder\\test2.pdf:application/pdf}\n}\n\n@article{zoteroFilePaths4,\n    title = {Zotero: linked attachments},\n    file = {Test:E\\:\\\\some\\\\random\\\\folder\\\\test2.pdf:application/pdf}\n}\n\n@article{mendeleyFilePaths1,\n    title = {Mendeley: single attachment},\n    url = {https://forums.zotero.org/discussion/28347/unable-to-get-pdfs-stored-on-computer-into-zotero-standalone/},\n    file = {:C$\\backslash$:/Users/somewhere/AppData/Local/Mendeley Ltd./Mendeley Desktop/Downloaded/test.pdf:pdf}\n}\n\n@article{mendeleyFilePaths2,\ntitle = {Mendeley: escaped characters}\nfile = {:C$\\backslash$:/some/path/,.$\\backslash$;'[]\\{\\}`-=\\~{}!@\\#\\$\\%\\^{}\\&()\\_+.pdf:pdf},\n}\n\n@article{citaviFilePaths1,\n    title = {Citavi: single attachment},\n    url = {https://forums.zotero.org/discussion/35909/bibtex-import-from-citavi-including-pdf-attachments/},\n    file = {Test:Q\\:\\\\some\\\\random\\\\folder\\\\test.pdf:pdf}\n}",
Dryad Digital Repository.js:            item.extra = '{:itemType: dataset}';
Dryad Digital Repository.js:                            "extra": "{:itemType: dataset}",
Dryad Digital Repository.js:                            "extra": "{:itemType: dataset}",
Dryad Digital Repository.js:                            "extra": "{:itemType: dataset}",
Google Scholar.js:              this.v.extra = "{:jurisdiction: " + jurisdiction + "}";
Google Scholar.js:                              "extra": "{:jurisdiction: Ohio}",
Google Scholar.js:                              "extra": "{:jurisdiction: Ohio}",
Google Scholar.js:                              "extra": "{:jurisdiction: Ohio}",
Google Scholar.js:                              "extra": "{:jurisdiction: SD Ohio}",
Juris.js:               item.extra += "{:jurisdiction: europa.eu}";
Juris.js:               item.extra += "{:jurisdiction: de}";
Juris.js:               item.extra += "\n{:genre: Beschl.}";
Juris.js:                       item.extra += "\n{:genre: Urt.}";
Juris.js:                               "extra": "{:jurisdiction: de}\n{:genre: Beschl.}",
Juris.js:                               "extra": "{:jurisdiction: de}\n{:genre: Beschl.}",
Juris.js:                               "extra": "{:jurisdiction: de}\n{:genre: Urt.}",
Juris.js:                               "extra": "{:jurisdiction: de}\n{:genre: Urt.}",
Juris.js:                               "extra": "{:jurisdiction: europa.eu}\n{:genre: Urt.}",
Juris.js:                               "extra": "{:jurisdiction: de}\n{:genre: Urt.}",
JurPC.js:                       item.extra = "{:genre: Beschl.}";
JurPC.js:                               item.extra = "{:genre: Urt.}";
JurPC.js:                               "extra": "{:genre: Urt.}",
JurPC.js:                               "extra": "{:genre: Urt.}",
JurPC.js:                               "extra": "{:genre: Beschl.}",
NCBI Nucleotide.js:             item.extra = "{:itemType: dataset}";
NCBI Nucleotide.js:                     item.extra += "\n{:version: " + version[1] + "}";
NCBI Nucleotide.js:                             "extra": "{:itemType: dataset}",
NCBI Nucleotide.js:                             "extra": "{:itemType: dataset}\n{:version: 4}",
```

Should these translator updated? @fbennett Are there any consequences for Juris-M?

Inspired by https://github.com/zotero/zotero/pull/1089

### PR DESCRIPTION
**Pull request by bwiernik**
Fixes #1143

### CODE REVIEW

**Comment by zuphilip** [comment]
Thank you @bwiernik ! Changing the old syntax looks fine. Can you also explain whether the uppercase writing is needed or just supported as well?

You need also to bump the timestamps for the translators you are changing. Otherwise they will not get deployed through the update mechanism.

For the legal fields we should also consult with @fbennett as they should then be in a way that is supported by Juris-M.

**Comment by bwiernik** [comment]
Uppercase is also supported by Zotero and generally preferred by Dan. 

Sorry about timestamps—I had assumed those would be auto-updated like in the CSL styles repo.

**Comment by zuphilip** [comment]
Okay, then I just want to wait for Frank to see whether this is also supported by Juris-M. You changed something for this recently in Zotero and I don't think this is already integrated in Juris-M as well, cf. https://github.com/Juris-M/zotero/commits/jurism-5.0 .

**Comment by zuphilip** [comment]
And update the timestamps at some point as we need this in the end.

**Comment by bwiernik** [comment]
I’ll check it out and make a PR on Jurism too

**Comment by fbennett** [comment]
Thanks, Brenton. I'll take a look at the changes when they arrive -- I try
to merge translator changes at each Jurism release, and there is one coming
up on the horizon.

(The main differences in the small population of Jurism-specific
translators are the capture and mapping of identifiers into "jurisdiction"
and "court" fields, and the use of a couple of Jurism-only helper functions
to add variants to creators and ordinary fields.)

Frank

**Comment by zuphilip** [comment]
This will then fix #1143.

**Comment by AbeJellinek** [comment]
@bwiernik, when you get a chance, could you resolve the conflict and update timestamps? This would be good to get merged!

**Comment by bwiernik** [comment]
@zuphilip @AbeJellinek done.

**Comment by AbeJellinek** [comment]
Thanks for doing that. Merged this in.

**Pull request merged**
