### PR TITLE
GMS German Medical Science.js: English website

### PR DESCRIPTION
**Pull request by sebastian-de**
The journal website is available in German and English, the translator
works identically for both.

### CODE REVIEW

**Comment by zuphilip** [comment]
This looks fine. Thank you! Did you run the test cases again?

**Comment by zuphilip** [comment]
Okay, thank you for the update. @sebastian-de Is this ready to merge from your side?

**Comment by sebastian-de** [comment]
Sorry for the delay -  yes, this is ready to merge from my side.

**Comment by zuphilip** [comment]
Thank you @sebastian-de !

**Pull request merged**
