### PR TITLE
Put NDPR review in snapshot

### PR DESCRIPTION
**Pull request by retorquere**

### CODE REVIEW

**Comment by adam3smith** [comment]
would you mind squashing these two? Looks good otherwise.

**Comment by retorquere** [comment]
If I can bother you for guidance on this once again, gladly.

**Comment by adam3smith** [comment]
short: https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit
long: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html
If you don't have git set up locally (though I'm assuming you must have), let me know and I'll just commit for you tonight.

**Comment by dstillman** [comment]
And you can use `fixup` instead of `squash` to avoid having to edit out the second commit message.

Also, counting commits is easy here, but for more involved PRs, you can do `git log` and manually find the commit before the first one in the PR and use that instead of `HEAD~n` for the `rebase -i`. In this case that's `e46b0004`. (`git merge-base HEAD master` can also work.)

**Comment by retorquere** [comment]
`git merge-base HEAD master` gives me `9fb18c554f2a0cc53bf2600a5e5ca57dd103c842`, which I can't find in the recent history.

I tried `git rebase -i e46b0004`, and after some scary messages, I think I managed to push out a squashed version.

For all the great things git does, squashing is the one thing where this ole' vi-head is pining for a GUI that walks me through it.

**Comment by adam3smith** [comment]
no kidding. I have done this a bunch now, I'm still giddy every time it works. Thanks!

**Pull request merged**
