### PR TITLE
Add "edition" to the typeMapping

### PR DESCRIPTION
**Pull request by mvolz**
Add edition to be treated like a book. Example item that is an edition: https://www.wikidata.org/wiki/Q14944010

### CODE REVIEW

**Comment by zuphilip** [comment]
Looks good! But you should also bump the time-stamps for triggering an update to the Zotero users.

**Comment by mvolz** [comment]
Thanks, done :).

**Comment by adam3smith** [comment]
Thanks @mvolz 

@zuphilip the timestamp is another candidate for automated tests. If we could check whether anything other than tests have changed and then require a timestamp update?

**Comment by zuphilip** [comment]
@adam3smith Good idea. I guess it should be possible by adapting the `checkDeletedTxt.sh`. Can you create an issue for this?

**Pull request merged**
