### PR TITLE
Fix itemType detection and add ISBN to Internet Archive metadata

### PR DESCRIPTION
**Pull request by mvolz**
Books on IA have ISBNs but this info isn't being
scraped. Add support to add this info.

Add book to tests with ISBN (Example URL)
https://archive.org/details/darktowersdeutsc0000enri/mode/2up

### CODE REVIEW

**Comment by mvolz** [comment]
This work but for some reason the 10 digit isbns aren't making it into the final citation... do those get cleaned out or something upstream?

**Comment by adam3smith** [comment]
which citation output (how generated) are you referring to?
Zotero does have a clean.ISBN function that might discard the second ISBN, but I'm not sure where it would be run automatically (as opposed to being called explicitly in the translator)

**Comment by mvolz** [comment]
> which citation output (how generated) are you referring to?
> Zotero does have a clean.ISBN function that might discard the second ISBN, but I'm not sure where it would be run automatically (as opposed to being called explicitly in the translator)

The test case I added,  https://archive.org/details/darktowersdeutsc0000enri/mode/2up 

When I do ZU.debug(newItem.ISBN) the field has 4 isbns, but when I use the translator file and curl it the isbn 10s are missing. I'm not too bothered by that if you aren't but I was wondering if that was a symptom of something going wrong! 

```
curl -d 'https://archive.org/details/darktowersdeutsc0000enri/mode/2up' -H 'Content-Type: text/plain' http://127.0.0.1:1969/web

[{"key":"9S6E5TKU","version":0,"itemType":"book","creators":[{"firstName":"David","lastName":"Enrich","creatorType":"author"},{"name":"Internet Archive","creatorType":"contributor"}],"tags":[{"tag":"Trump, Donald, 1946-","type":1}],"title":"Dark towers : Deutsche Bank, Donald Trump, and an epic trail of destruction","abstractNote":"x, 402 pages ; 24 cm; \"A searing exposé by an award-winning journalist of the most scandalous bank in the world, including its shadowy ties to Donald Trump's business empire\"--; Includes bibliographical references (pages 367-390) and index; \"A searing expose by an award-winning journalist of the most scandalous bank in the world, including its shadowy ties to Donald Trump's business empire\"--","date":"2020","publisher":"New York, NY : Custom House","language":"eng","numPages":"426","ISBN":"9780062878816 9780062878830","url":"http://archive.org/details/darktowersdeutsc0000enri","libraryCatalog":"Internet Archive","accessDate":"2020-03-06T13:45:37Z","shortTitle":"Dark towers"}]
```

**Comment by mvolz** [comment]
PS I've linted a little, do you prefer it to go as additional commits in this thread, or as a separate PR?

**Comment by adam3smith** [comment]
linting in the same PR, different (non-squashed, obv) commit, please. Thanks!

**Comment by adam3smith** [comment]
@mvolz add your linted update when you get a chance?

**Comment by mvolz** [comment]
> @mvolz add your linted update when you get a chance?

I never finished it! But in the meantime it looks like IA type detection is broken, which I've added to the commit. I'll try to finish the linting too.

**Comment by mvolz** [comment]
There are now only two lines left to lint: 
   39:10  error  Expected to return a value at the end of function 'detectWeb'  consistent-return
  225:52  error  Expected to return a value at the end of function              consistent-return

I actually wasn't sure how to handle those because I'm not familiar enough with the code base >.<

**Comment by adam3smith** [comment]
Thanks! -- I fixed those two things.
Could you 
1) make sure the tests are updated (Zotero now runs those in CI and it looks like there are some differences, but those may also been due to different locations)
2) pull my two commits and then rebase&squash this into 2 commits, one substantive the other one all the linting changes?

**Comment by mvolz** [comment]
> Could you
> 
> 1. make sure the tests are updated (Zotero now runs those in CI and it looks like there are some differences, but those may also been due to different locations)
> 2. pull my two commits and then rebase&squash this into 2 commits, one substantive the other one all the linting changes?

Okay, this is now all done; I fixed the tests and squashed it into two. I think the tests are okay, it seems to be a few upstream changes, and my local environment doing odd things, and not that anything is broken.

**Comment by dstillman** [comment]
Thanks!

What was "locally" in this case that was giving different output? The CI test runner is brand new, so there might still be some kinks to work out.

**Comment by dstillman** [comment]
(And sorry for the delay here. Part of the goal of the CI test runner is that we'll be able to review these much quicker as long as they have proper tests.)

**Comment by mvolz** [comment]
> Thanks!
> 
> What was "locally" in this case that was giving different output? The CI test runner is brand new, so there might still be some kinks to work out.

It might just be the fact that I was manually testing with translation-server; it looks like your ci tests runs chrome and uses zotero in the browser? 

The main differences were: 

-           "name": "Internet Archive"
            "creatorType": "contributor"
+           "lastName": "Internet Archive"
+           "fieldMode": 1

Locally it's wrong, the results are better in CI. And then locally the tags have a type, i.e. 

,{"tag":"richard nixon","type":1} locally, but in CI the tags don't have a type and they're just listed.

**Pull request merged**
