### PR TITLE
Twitter: Support localization where am/pm are lowercase

### PR DESCRIPTION
**Pull request by tfiers**
Tests run succesfully now.

### CODE REVIEW

**Comment by dstillman** [comment]
I think this is a misunderstanding. I'm not sure what this fixes, but it certainly wouldn't add support for the new Twitter layout, which is a complete redesign of the site, with entirely different — and essentially unparseable — DOM. It seems like you're still viewing the old version.

**Comment by dstillman** [comment]
And I would guess that the am/AM thing is non-US localization, so this wouldn't be an appropriate fix for that either. I still get "AM" in the old design (and the new one).

**Comment by dstillman** [comment]
So while we'd take a patch to make the date detection case-insensitive (though it'd be good to figure out what's triggering the difference — `Accept-Language`, IP geolocation, a Twitter localization setting?), saving on Twitter will be broken in general for most people (possibly anyone logged in?) at this point.

**Comment by zuphilip** [comment]
In the new Twitter UI I see either `<time datetime=...>` or `data-time-ms` which would be easier to parse. Are they not present in the old UI?

**Comment by dstillman** [comment]
`data-time` and `data-time-ms` attributes do appear to exist in the old UI.

**Comment by dstillman** [comment]
(And in the new UI, it's unfortunately not that simple. If you're focused on a reply, only the original tweet has a `<time>`. The reply you're focused on just has a `<span>` with gibberish CSS class names.)

**Comment by zuphilip** [comment]
@dstillman I switched Zotero to English (UK), restart it, and then opened the Twitter website in Scaffold and see there the small `am`. It is large with the English ((not UK))  settings.

**Comment by tfiers** [comment]
Hi @dstillman and @zuphilip. Thanks for the quick responses.
Last commit makes the date parsing case-insensitive.

I indeed got the old UI when running tests.

For the new UI with the gibberish CSS classes, seems like a combination of searching for <article> and navigating lots of div>div>div> hierarchies might do it?

**Comment by zuphilip** [comment]
Thank you @tfiers for the support of different localization of am/pm! I squashed the commits together and merged it. :rocket:

The new website layout of Twitter is a different story, but we can continue this in the other issue.

**Pull request merged**
