### PR TITLE
upgrade to eslint:notice makes 'template' unnecesary.

### PR DESCRIPTION
**Pull request by retorquere**

### CODE REVIEW

**Comment by dstillman** [comment]
You'll need to rebase and force-push this to avoid the duplicate commits.

**Comment by retorquere** [comment]
I was wondering about that... I know you've explained before, but what are the steps to do this? Rebasing is the one git concept that keeps eluding me.

**Comment by dstillman** [comment]
Depends how you have things set up and the current state, but something like this should do it:

```
git fetch upstream master
git rebase -i origin/master
```

(This is assuming you have `upstream` set as the remote for `zotero/translators` (as shown in `git remove -v`).)

If all goes well, you should see an editor window with only the relevant commit. You can then run `git push -f` to force-push it to this branch.

**Comment by dstillman** [comment]
Oh, and you'll need to delete the extra commits in the editor window during the interactive rebase, since those are commits that don't exist upstream (since I squashed them into a single commit in the other PR). So you just want to leave the last line, which is the relevant commit.

(In the future, the way to avoid this is to start a new branch based on the latest upstream master rather than anything you have locally.)

**Comment by retorquere** [comment]
How do I do that? I merged upstream/master into my master and had hoped to avoid this by doing that. Can I checkout upstream/master and branch that?

**Comment by dstillman** [comment]
How do you do what?

**Comment by dstillman** [comment]
If you mean how do you delete commits, you just delete the lines in the editor during the interactive rebase. It gives instructions in the window.

This happened because, somehow or another, you based this branch on your PR rather than on the merged master.

**Comment by retorquere** [comment]
I really thought I did base the branch on the merged master. I'll figure this out and resubmit.

**Comment by retorquere** [comment]
I meant how do I start a new branch based on the latest upstream master rather than anything you have locally, because I did just that.

**Comment by dstillman** [comment]
(There's pretty much never a need to delete a pull request. You can always fix the branch and force-push, and it's almost always better to do that.)

**Comment by retorquere** [comment]
Wait, that's what's gone wrong then. I have a local branch named `eslint-notice-0.7.8`, and this pull request is meant to come from that. I did delete the `eslint` branch but that is what was merged earlier.

**Pull request closed without merging**
