### PR TITLE
adaptation for the new catalog

### PR DESCRIPTION
**Pull request by facem**
Hello
I'm making a pull request.
The changes consist on :
the Import works whatever display style (intermarc, unimarc, public)
in the field 'URL' there is a ARK link of the notice
the URL of numeric document is in  field "attachement document"
correction for the role detection
The document type detection uses the field Unimarc
Modification of the field "source" 
thank you
Best regard

### CODE REVIEW

**Comment by dstillman** [comment]
(Note sure if you meant to close this, but note that, if you want to make changes, you should make them locally, squash the commits (or do an amend in git), and force-push to this branch to update this PR rather than opening a new PR.)

**Comment by dstillman** [comment]
Also please use a more specific PR title and commit message to identify the translator this is for.

**Comment by adam3smith** [comment]
@dstillman -- not sure if you saw, but github now allows squash on merge. It works great: https://github.com/blog/2141-squash-your-commits

**Comment by adam3smith** [comment]
(and @facem  -- at first glance, the proposed changes look good, so we would like this pull request)

**Comment by dstillman** [comment]
(Yeah, I know — just figured for an initial commit a squashed commit would be better, since reviewers shouldn't need to write commit messages themselves even if they're squashing post-review commits. But you're right, not a big deal if not squashed.)

**Comment by facem** [comment]
Hello
I am sorry for my mistake and my message but I don't understand what I must
do.
Thank you for your help.

**Comment by facem** [comment]
Hello
I'm pushing a new message commit.
Thank you for your help
best regard

2016-04-12 23:13 GMT+02:00 facem facem <bfacem@gmail.com>:

> Hello
> I am sorry for my mistake and my message but I don't understand what I
> must do.
> Thank you for your help.

**Comment by facem** [comment]
Hello
I pushed (commit -a and pull -f) but I can't reopen the PR

Could  you help me ?

Thank you for your help
Best regard.

2016-04-13 18:13 GMT+02:00 facem facem <bfacem@gmail.com>:

**Comment by dstillman** [comment]
I think maybe it can't be reopened after a short period of time, so you'll have to open a new one.

**Comment by facem** [comment]
Ok,
thank

2016-04-15 8:54 GMT+02:00 Dan Stillman <notifications@github.com>:

**Comment by facem** [comment]
Hello
I openned au new PR.
I hope that's ok.
Thank you for your help and patience
Best regard

2016-04-15 12:37 GMT+02:00 facem facem <bfacem@gmail.com>:

**Pull request closed without merging**
