### PR TITLE
Fixes #703

### LINKED ISSUE #703: IACR eprint translator broken
The IACR translator is not working:

https://eprint.iacr.org/2014/218

### PR DESCRIPTION
**Pull request by FredericJacobs**

### CODE REVIEW

**Comment by adam3smith** [comment]
this doesn't work, unfortunately -- while the attachment request come out OK, Zotero doesn't automatically convert the string saved to the URL field into an absolute link (which it should be for printing). You probably need to create a separate variable and then tag on either the correct http/https or just default to https for the URL.

Also, you need to update the date field and re-run/update tests -- strongly recommended doing so in scaffold. https://www.zotero.org/support/dev/translators/scaffold

**Comment by FredericJacobs** [comment]
Thanks, will open a new PR when I have figured it out.

**Comment by aurimasv** [comment]
You're also using Chrome connector without Standalone, right? (I think that's the only way you would get the errors you are getting). You're welcome to continue doing so, but not having Standalone open will sometimes result in poorer metadata quality and may be noticeably slower.

**Comment by FredericJacobs** [comment]
Correct. Just installed Zotero Standalone and it works now.

**Comment by aurimasv** [comment]
The error you're reporting should still not happen though, so if you want to submit a patch for it, we'll accept it. If not, we'll end up fixing this at some point.

**Pull request closed without merging**
