### PR TITLE
Revert "Change version to versionNumber for computerProgram"

### PR DESCRIPTION
**Pull request by adam3smith**
Reverts zotero/translators#1084

### CODE REVIEW

**Comment by zuphilip** [comment]
Hm.. I see that there is a problem in Ubuntu but in Windows it seems to work. I tried the CSV translator with `"minVersion": "4.0.27",` but it works with `"minVersion": "4.0.26",` and every smaller number. The error message seems quite clear:
```
(2)(+0000001): Translate: Translation using CSV failed: 
string => TypeError: item.uniqueFields is undefined
stack => getValue@CSV:211:1
doExport@CSV:110:7
```
@dstillman Any ideas what is going on? Was there any change for `uniqueFields` in this version?

**Comment by dstillman** [comment]
I don't really know anything about the `uniqueFields` stuff, sorry.

**Comment by aurimasv** [comment]
There are no `uniqueFields` in the API version of Zotero.Item JSON. https://github.com/zotero/zotero/blob/master/test/tests/data/translatorExport.js

**Comment by zuphilip** [comment]
Is `uniqueFields` old code and only supported for legacy translators (pre 4.0.27) via [addCompatibilityMappings](https://github.com/zotero/zotero/blob/4.0/chrome/content/zotero/xpcom/utilities_internal.js#L421)?

Please let me know whether it is true that: By increasing the `minVersion` to `4.0.27` the function `addCompatibilityMappings` will not be called. This could explain the problems with the translators commit...

**Comment by aurimasv** [comment]
>Please let me know whether it is true that: By increasing the `minVersion` to 4.0.27 the function `addCompatibilityMappings` will not be called

That is correct.

**Pull request merged**
