### PR TITLE
Added translator for ISMRM proceedings

### PR DESCRIPTION
**Pull request by fsantini**
ISMRM (International Society of Magnetic Resonance in Medicine) hosts the proceedings of the annual conference in HTML format since 2016. This is a scraper translator that creates a zotero entry for abstracts, either from a search page or from a single abstract page.

### CODE REVIEW

**Comment by adam3smith** [comment]
Thanks. So at a high level -- this uses a lot of legacy code that makes it a) hard to maintain and b) not work well in some cases (in particular multiple saves). What did you base this on? 

The best current guidance is at https://www.mediawiki.org/wiki/Citoid/Creating_Zotero_translators
If you need Xpaths, use `ZU.xpath` and `ZU.xpathText` instead of `doc.evaluate`.  See https://www.zotero.org/support/dev/translators/coding

We'd also want tests and a license statement, please.

**Comment by fsantini** [comment]
Thank you for the feedback. I based it on the tutorial from the official zotero pages... It's hard for a new developer to understand what guidelines to follow, and honestly I wouldn-t have imagined that the best practice was actually indicated on a different domain than the zotero one. I will cancel the pull request and rewrite the translator according to the page you indicated then.

⁣Sent from BlueMail ​

**Comment by adam3smith** [comment]
The bit at wikimedia is just great because they just updated it to reflect best practices.

You mean you followed this? https://www.zotero.org/support/dev/how_to_write_a_zotero_translator_plusplus We should probably take it down entirely, but it does have a note that it's outdated at the top. Or is there something else that mentions `doc.evaluate` code everywhere?

**Comment by zuphilip** [comment]
> I will cancel the pull request and rewrite the translator according to the page you indicated then.

@fsantini Any update on this?

**Comment by fsantini** [comment]
No sorry, the proper documentation is not easy to find and motivation is low ATM as it works fine for me... If anybody wants to have a stab at it, you're of course very welcome. I'm closing this PR now. Thank you all for the feedback.

**Pull request closed without merging**
