### PR TITLE
RIS - Thesis : add contributor field

### PR DESCRIPTION
**Pull request by stl74**
RIS format doesn't export contributor for thesis document type.
Needed to add thesis supervisor as contributor , added as "A2"

### CODE REVIEW

**Comment by AbeJellinek** [comment]
Could we use A3 instead? That's what ProQuest Dissertations uses and it seems more appropriate.

**Comment by adam3smith** [comment]
(RIS specs also say A3)

**Comment by adam3smith** [comment]
Tests are just timing out -- merging this.

**Comment by adam3smith** [comment]
Thanks!

**Pull request merged**
