### PR TITLE
Update Translator Der Freitag

### PR DESCRIPTION
**Pull request by JLueke**
Rewrite and update Translator for "Der Freitag" with Embedded Metadata as base translator.

### CODE REVIEW

**Comment by JLueke** [comment]
The lint script in package json should be updated. There was no error with the command documented here:
https://www.zotero.org/support/dev/translators

`npm ci && npm run lint -- "Your Translator.js"`

**Comment by AbeJellinek** [comment]
You have to replace `"Your Translator.js"` with the translator filename. (It should return an error when passed an invalid filename - will fix.)

**Comment by JLueke** [comment]
> You have to replace `"Your Translator.js"` with the translator filename. (It should return an error when passed an invalid filename - will fix.)

I know that. For me the "lint" script didn't worked. Using the _eslint_ command directly worked, _testlint_ didn't.

**Comment by AbeJellinek** [comment]
Hmm, that's odd. Did it give you any output at all?

**Comment by AbeJellinek** [comment]
(`eslint` works fine but doesn't support some Zotero-specific linters that use a cache of translator data.)

**Pull request merged**
