### PR TITLE
Update selenium test to support `system-app`

### PR DESCRIPTION
**Pull request by saschanaz**
For now I did this, but can we use something like this: https://developer.chrome.com/docs/extensions/reference/manifest/key#keep-consistent-id ?

### CODE REVIEW

**Comment by dstillman** [comment]
Can you explain what this is for?

**Comment by saschanaz** [comment]
It's to fix the CI failure: https://github.com/zotero/translators/pull/3209#issuecomment-1864770355

**Comment by saschanaz** [comment]
It seems that didn't work: https://github.com/zotero/translators/actions/runs/7469963343/job/20327889161

Are you sure the extension ID is guaranteed to be constant?

**Comment by saschanaz** [comment]
Hmm, actually that failure happens earlier than getting the URL, hmm.

**Comment by aborel** [comment]
In https://github.com/zotero/translators/actions/runs/7469963343/job/20327889161 it seems that ```translatorServer.filenameToTranslator[translatorFilename]``` is undefined (for some value of ```translatorFilename```.  The lint test in the same log is run on ```TinREAD.js```, which is apparently part of another PR https://github.com/zotero/translators/pull/3223#commits-pushed-a85b22f . Based on the comments there, maybe the file should not even be there at all?

**Comment by saschanaz** [comment]
Per https://github.com/zotero/translators/actions/runs/7540520982/job/20525278512 no, they all look proper files with metadata.

**Comment by saschanaz** [comment]
Submitted #3231.

**Comment by saschanaz** [comment]
Alright, #3213 is green now, I'll close this one. Thanks!

**Pull request closed without merging**
