### PR TITLE
Update Eurogamer for March 2018 redesign

### PR DESCRIPTION
**Pull request by owcz**
- updated translator to work post-redesign
- combined similar Eurogamer and USgamer translators (same owner, slightly different code)
- expanded detect to Eurogamer in other languages
- removed Framework #1277, now starts from EM

### CODE REVIEW

**Comment by owcz** [comment]
`e570f517-83f2-4735-97d2-44499aee0b21` was renamed, not deleted, so false alarm on Travis CI, I think

**Comment by adam3smith** [comment]
@zuphilip if you have a chance to look at the false positive test above at some point, that'd be great.

**Comment by adam3smith** [comment]
Thanks!

**Comment by zuphilip** [comment]
@adam3smith Renames are difficult to detect for the script. This works only reliable when you use `git mv` for that. See also https://github.com/zotero/translators/pull/1357

**Comment by adam3smith** [comment]
Ah yes, thanks. OK, we'll just know to double-check & ignore the test in those cases then

**Pull request merged**
