### PR TITLE
Add conference name for ACLAnthology translator

### PR DESCRIPTION
**Pull request by GuyAglionby**
Addresses #1734 . This adds an abbreviated conference name to ACL imports, except those that:

* Have `WS` as a venue, indicating that the paper is from a workshop
* Have `Student`, `Demonstration`, or `Tutorial` in the conference title, as these are not part of the main conference.

@nschneid can you please confirm if this seems reasonable? Thanks!

### CODE REVIEW

**Comment by nschneid** [comment]
Awesome! The only other thing I would suggest is special-casing *SEM/SemEval, which right now are listed as [*SEMEVAL](https://aclanthology.coli.uni-saarland.de/venues/semeval)—note the variation in titles over the years.

Suggested heuristic based on the proceedings title:

1. If it contains "SENSEVAL", return "SENSEVAL".
2. Else if it contains "Evaluation" and not "Joint", return "SemEval".
3. Else if it contains "Joint" and not "Evaluation", return "*SEM".
4. Else if it contains "Volume 1" and "Volume 2", return "*SEM/SemEval". (special case for 2012, where the numeric prefixes on papers do not distinguish the two volumes)
5. Else if it contains "SemEval", return "SemEval".
6. Else return "*SEM".

**Comment by nschneid** [comment]
The *SEMEVAL heuristics should be applied before filtering out WS venues, as SENSEVAL in 2004 is also listed as WS.

**Comment by GuyAglionby** [comment]
Thanks for supplying those heuristics @nschneid . The solution now looks something like:

* If the proceedings name includes 'Student', 'Demonstration', or 'Tutorial', assume there is no conference name.
* If the proceedings name contains '*SEMEVAL', apply the heuristics you provide to get the name.
* Otherwise, scrape the name from the 'Venues' table row on the website, unless this contains 'WS', in which case do not return anything.

**Comment by nschneid** [comment]
Looks great, thanks!

**Comment by nschneid** [comment]
@adam3smith is this ready to merge?

**Comment by Evpok** [comment]
If I understand correctly, this will use the initialized name (ie ACL 2019 instead of xth Annual Meeting of the Association for Computational Linguistics). Is it the usual way to do this in Zotero? E.g. in BibLaTeX, the full name is the event name and the abbreviation is an event title addon (https://github.com/plk/biblatex/issues/122).

**Comment by mjpost** [comment]
Also, isn't this referencing the wrong version of the Anthology? I see references to the Saarland server in the diff.

**Comment by nschneid** [comment]
Zotero has two fields for conference papers, Proceedings Title and Conference Name. This will put the abbreviation in Conference Name. That way the user can choose whether the exported bibliography/BibTeX has the short name or the full proceedings title.

**Comment by Evpok** [comment]
@nschneid I understand, that is certainly nitpicking on my part, but I thought that the two fields existed in case the proceedings had a title other than simply “Proceeding of <conference name>”

**Comment by nschneid** [comment]
Well, for the original intent you'd have to ask those who decided on the fields, but Proceedings Title is already populated based on booktitle, so Conference Name is a convenient place to store the abbreviation.

**Comment by GuyAglionby** [comment]
> Also, isn't this referencing the wrong version of the Anthology? I see references to the Saarland server in the diff.

Yes, this targets the old version. This change(/translator) will be superseded once aclanthology.info redirects to aclweb.org/anthology, the translator for which will have to be re-written anyway but can include this facility.

**Comment by GuyAglionby** [comment]
https://aclanthology.info has been shut down; #1911 supersedes this

**Pull request closed without merging**
