### PR TITLE
Add Le Maitron

### PR DESCRIPTION
**Pull request by owcz**
This is a major French set of encyclopedias with open online access. No metadata => all manual scrape.

### CODE REVIEW

**Comment by owcz** [comment]
Also noticed that `ZU.strToISO` struggles with certain French dates. It only retains the year from `14 avril 2014` and `16 mai 2014`

`30 décembre 2010` doesn't work without removing the diacritic with `.normalize('NFD').replace(/[\u0300-\u036f]/g, "")`

Not a big deal for this translator in particular, but worth flagging in general

**Comment by dstillman** [comment]
> Also noticed that ZU.strToISO struggles with certain French dates. It only retains the year from 14 avril 2014 and 16 mai 2014

That's a little tricky. Zotero handles all of those dates, but only if the current locale is French.

The options here are basically 1) supporting an optional locale that could be passed to the `strTo*` functions or 2) trying to parse dates from all locales, regardless of the current locale.

**Comment by retorquere** [comment]
If you know the dates on the website are always french, you could use string replace to change the french months into their english equivalents before handing it to strToISO.

**Comment by AbeJellinek** [comment]
Thanks, this looks good. I rebased, linted, added a simple date translator, and updated the tests. Merging.

**Comment by owcz** [comment]
The translator is failing on a few articles. Noting here for me to review later:
* https://maitron.fr/spip.php?article153818

**Pull request merged**
