### PR TITLE
Translate tweets as forum posts

### LINKED ISSUE #2579: Tweets: forum posts or blog posts?
We currently scrape tweets as blog posts, but [the wiki](https://www.zotero.org/support/kb/item_types_and_fields) recommends classifying them as forum posts:

Forum Post | A post on an online discussion forum. Also use this type for items such as Facebook posts or tweets.
-- | --

It seems like either the translator or the documentation should change.

### PR DESCRIPTION
**Pull request by AbeJellinek**
See https://github.com/zotero/translators/issues/2579#issuecomment-1021801458.

Closes #2579

### CODE REVIEW

**Comment by AbeJellinek** [comment]
@adam3smith / @bwiernik: Is putting the Twitter username in square brackets at the end of the creator name relatively good across citation styles? See the updated tests. I'm going off of what the APA test library does.

**Comment by adam3smith** [comment]
I think that's good, yes. Few styles are as explicit as APA

**Comment by bwiernik** [comment]
It's the best compromise. A future version of CSL will likely have a specific field in the name structure to hold things like this.

**Comment by AbeJellinek** [comment]
Alright, great, thank you! I'll merge this, then.

**Pull request merged**
