### PR TITLE
Update ACL to handle new paper id format

### PR DESCRIPTION
**Pull request by GuyAglionby**
Update the translator to handle the new paper ID format, which is detailed in the second FAQ point [here](https://www.aclweb.org/anthology/faq/). Couple of other minor changes to reflect new site layout.

### CODE REVIEW

**Comment by adam3smith** [comment]
Travis report (passing) is here:
https://travis-ci.org/github/zotero/translators/builds/695461174

**Comment by nschneid** [comment]
This is to fix #2185. Ready for merge?

**Comment by GuyAglionby** [comment]
The ACL 2020 proceedings are now [online](https://www.aclweb.org/anthology/events/acl-2020/) with the new ID format, and the conference is in a couple of weeks. Would like to get this out if possible before then - please let me know if any changes are required and I'll get to them asap.

**Comment by adam3smith** [comment]
Thanks!

**Pull request merged**
