### PR TITLE
Added support for Amazon Smile

### PR DESCRIPTION
**Pull request by LiberalArtist**
Modified the Amazon.com.js translator to also match URLs for the Amazon Smile charitable donation program (smile.amazon.com)

### CODE REVIEW

**Comment by adam3smith** [comment]
Thanks. This is fine, but you need to update the timestamp, otherwise this won't actually update for Zotero users. If you know how to, update your pull request, rebase&squash. Otherwise we'll just put this in directly from our side.

**Comment by LiberalArtist** [comment]
I (think) I just took care of it. (I'm pretty new to GitHub, so apologies if I've not gotten that quite right.)

**Comment by adam3smith** [comment]
we're trying to keep the commit history clean, so we'd generally ask you to rebase&squash this:
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html into a single commit,
but you can also just let us know if that's taking it to far; it's not much work to just push your style fix.

**Comment by LiberalArtist** [comment]
Ok, I think I've squashed them successfully.

**Comment by adam3smith** [comment]
you did indeed, thanks!

**Pull request merged**
